### ISSUE TITLE
Criar Roadmap

### ISSUE THREAD

**Issue by Ermesoml** [remotejobsbr/remote-jobs-client#6]
Creio que deveria criar um Roadmap para que possamos focar no que falta fazer, além de acompanhar o desenvolvimento da ferramenta.

**Comment by IsTheJack** [comment]
Excelente ideia, @Ermesoml. Tem algum modelo de algum outro projeto open source que gostaria que a gente se baseasse?

**Comment by IsTheJack** [comment]
Não é bem um roadmap por enquanto, mas são algumas coisas que faltam no projeto e eu vou listar nessa issue temporariamente até criar um arquivo de roadmap:

- [ ] Adicionar patrocidadores
- [ ] Desenvolver blog
- [ ] Desenvolver Newsletter
- [ ] Desenvolver cadastro de vagas internas (CRUD)
- [ ] Iniciar Backend
- [ ] Instalar Service Worker
- [ ] Adicionar pré commits (husky)
- [ ] Configurar testes (Jest / Cypress)
- [ ] Configurar lint

Sugestões de features são bem vindas. :D

**Comment by Ermesoml** [comment]
Creio que deva colocar um arquivo da forma como colocou a lista acima, mas separando as releases e indicando o que vai na próxima release.
